labels:
  - name: invalid-forum
    labeled:
      issue:
        body: |
          This is a bug tracker and not a support forum.

          While we'd love to be able to support every person on their projects, that would simply be infeasible. Luckily, that's what the helpful developer community over at Stack Overflow is for! Please [create a question there with the \"java-ngrok\" tag](https://stackoverflow.com/questions/ask?tags=java+java-ngrok+ngrok) if what you're looking for is a programming question or you need help with an integration. You can refer to [`java-ngrok's` own documentation](https://javadoc.io/doc/com.github.alexdlaird/java-ngrok) to help you write the best possible question.
        action: close
  - name: invalid-ngrok
    labeled:
      issue:
        body: |
          While `java-ngrok` is a wrapper for `ngrok`, we have no official affiliation with `ngrok` and thus cannot triage issues related to it.

          For help troubleshooting `ngrok`, ask a question on a support forum [like Stack Overflow](https://stackoverflow.com/questions/ask?tags=java+java-ngrok+ngrok). You can refer to [`java-ngrok's` documentation](https://javadoc.io/doc/com.github.alexdlaird/java-ngrok) and [`ngrok`'s documentation](https://ngrok.com/docs) to help you write the best possible question.
        action: close
